#include <stdio.h>

// The following are defined in table 2-9.  tm4c123gh6pm data sheet
// http://www.ti.com/lit/ds/symlink/tm4c123gh6pm.pdf

const char *Vectors [] =  {
  [0]   = "_estack",
  [1]   = "Reset_Handler",
  [2]   = "NMI_Handler",
  [3]   = "HardFault_Handler",
  [4]   = "MemMange_Handler",
  [5]   = "BusFault_Handler",
  [6]   = "UsageFault_Handler",
  /* reserved */
  [11]  = "SVC_Handler",
  [12]  = "DebugMon_Handler",
  /* reserved */
  [14]  = "PendSV_Handler",
  [15]  = "SysTickIntHandler",  // changed to ti naming "SysTick_Handler",
  [16]  = "GPIOA_IRQHandler",
  [17]  = "GPIOB_IRQHandler",
  [18]  = "GPIOC_IRQHandler",
  [19]  = "GPIOD_IRQHandler",
  [20]  = "GPIOE_IRQHandler",
  [21]  = "UART0_IRQHandler",
  [22]  = "UART1_IRQHandler",
  [23]  = "SSI0_IRQHandler",
  [24]  = "I2C0_IRQHandler",
  [24]  = "I2C0_IRQHandler",
  [25]  = "PWM0_Fault_IRQHandler",
  [26]  = "PWM0_GEN0_IRQHandler",
  [27]  = "PWM0_GEN1_IRQHandler",
  [28]  = "PWM0_GEN2_IRQHandler",
  [29]  = "QEI0_IRQHandler",
  [30]  = "ADC0_SEQ0_IRQHandler",
  [31]  = "ADC0_SEQ1_IRQHandler",
  [32]  = "ADC0_SEQ2_IRQHandler",
  [33]  = "ADC0_SEQ3_IRQHandler",
  [34]  = "WD_Timer0_1_IRQHandler",
  [35]  = "Timer0A_16_32_IRQHandler",
  [36]  = "Timer0B_16_32_IRQHandler",
  [37]  = "Timer1A_16_32_IRQHandler",
  [38]  = "Timer1B_16_32_IRQHandler",
  [39]  = "Timer2A_16_32_IRQHandler",
  [40]  = "Timer2B_16_32_IRQHandler",
  [41]  = "Analog_CMP0_IRQHandler",  
  [42]  = "Analog_CMP1_IRQHandler",  
  /* reserved */
  [44]  = "SYS_CTL_IRQHandler",  
  [45]  = "Flash_EEPROM_IRQHandler",  
  [46]  = "GPIOF_IRQHandler",  
  /* reserved */
  [49]  = "UART2_IRQHandler",  
  [50]  = "SSI1_IRQHandler",  
  [51]  = "Timer3A_16_32_IRQHandler",
  [52]  = "Timer3B_16_32_IRQHandler",
  [53]  = "I2C1_IRQHandler",
  [54]  = "QEI1_IRQHandler",
  [55]  = "CAN0_IRQHandler",
  [56]  = "CAN1_IRQHandler",
  /* reserved 57-58 */
  [59]  = "Hibernation_IRQHandler",
  [60]  = "USB0DeviceIntHandler",  // changed to match Tiva driver lib
  [61]  = "PWM0_GEN3_IRQHandler",
  [62]  = "uDMA_Software_IRQHandler",
  [63]  = "uDMA_Error_IRQHandler",
  [64]  = "ADC1_SEQ0_IRQHandler",
  [65]  = "ADC1_SEQ1_IRQHandler",
  [66]  = "ADC1_SEQ2_IRQHandler",
  [67]  = "ADC1_SEQ3_IRQHandler",
  /* Reserved 68-72 */
  [73]  = "SSI2_IRQHandler",
  [74]  = "SSI3_IRQHandler",
  [75]  = "UART3_IRQHandler",
  [76]  = "UART4_IRQHandler",
  [77]  = "UART5_IRQHandler",
  [78]  = "UART6_IRQHandler",
  [79]  = "UART7_IRQHandler",
  /* Reserved 80-83 */
  [84]  = "I2C2_IRQHandler",
  [85]  = "I2C3_IRQHandler",
  [86]  = "Timer4A_16_32_IRQHandler",
  [87]  = "Timer4B_16_32_IRQHandler",
  /* reserved 88-107 */
  [108]  = "Timer5A_16_32_IRQHandler",
  [109]  = "Timer5B_16_32_IRQHandler",
  [110]  = "Timer0A_32_64_IRQHandler",
  [111]  = "Timer0B_32_64_IRQHandler",
  [112]  = "Timer1A_32_64_IRQHandler",
  [113]  = "Timer1B_32_64_IRQHandler",
  [114]  = "Timer2A_32_64_IRQHandler",
  [115]  = "Timer2B_32_64_IRQHandler",
  [116]  = "Timer3A_32_64_IRQHandler",
  [117]  = "Timer3B_32_64_IRQHandler",
  [118]  = "Timer4A_32_64_IRQHandler",
  [119]  = "Timer4B_32_64_IRQHandler",
  [120]  = "Timer5A_32_64_IRQHandler",
  [121]  = "Timer5B_32_64_IRQHandler",
  [122]  = "System_Exception_IRQHandler",
  /* reserved 123-149 */
  [150]  = "PWM1_GEN0_IRQHandler",
  [151]  = "PWM1_GEN1_IRQHandler",
  [152]  = "PWM1_GEN2_IRQHandler",
  [153]  = "PWM1_GEN3_IRQHandler",
  [154]  = "PWM1_Fault_IRQHandler"
};

char *header = 
  "/* Generated by startup_generator */\n\n"
  "#include <stdint.h>\n"
  "#include <inc/hw_nvic.h>\n"
  "#include <inc/hw_types.h>\n\n"
  "extern void _estack(void);  // to force type checking\n"
  "void Reset_Handler(void);\n"
  "void default_handler (void) { while(1); }\n\n"
  "void __attribute__ ((weak)) __libc_init_array(void){}\n\n"
  "// Linker supplied pointers\n\n"
  "extern unsigned long _sidata;\n"
  "extern unsigned long _sdata;\n"
  "extern unsigned long _edata;\n"
  "extern unsigned long _sbss;\n"
  "extern unsigned long _ebss;\n\n"
  "extern int main(void);\n\n"
  "void Reset_Handler(void) {\n\n"
  "   unsigned long *src, *dst;\n\n"
  "   src = &_sidata;\n"
  "   dst = &_sdata;\n\n"
  "   // Copy data initializers\n\n "
  "   while (dst < &_edata)\n"
  "      *(dst++) = *(src++);\n\n"
  "   // Zero bss\n\n"
  "   dst = &_sbss;\n"
  "   while (dst < &_ebss)\n"
  "       *(dst++) = 0;\n\n"
  "  __libc_init_array();\n"
  " //\n"
" // Enable the floating-point unit.  This must be done here to handle the\n"
" // case where main() uses floating-point and the function prologue saves\n"
" // floating-point registers (which will fault if floating-point is not\n"
" // enabled).  Any configuration of the floating-point unit using DriverLib\n"
" // APIs must be done here prior to the floating-point unit being enabled.\n"
" //\n"
" // Note that this does not use DriverLib since it might not be included in\n"
" // this project.\n"
" //\n\n"
  " HWREG(NVIC_CPAC) = ((HWREG(NVIC_CPAC) & \n"
  "                     ~(NVIC_CPAC_CP10_M | NVIC_CPAC_CP11_M)) |\n"
  "                     NVIC_CPAC_CP10_FULL | NVIC_CPAC_CP11_FULL);\n"
  "  main();\n"
  "  while(1) {}\n"
  "}\n\n"
  "/* Vector Table */\n\n";

char *mid = 
  "\n\n\n__attribute__ ((section(\".isr_vector\")))\n\n"
  "void (* const g_pfnVectors[])(void) = {\n\n\t";


void DefineHandler(const char *s){
  fprintf(stdout, "void %s (void) __attribute__ ((weak,  alias (\"default_handler\")));\n", s);
}

void PrintVectorName (const char *s){
  static int zeros = 0;
  if (s) {
      if (zeros)
	fprintf(stdout, "\n\t");
      fprintf(stdout, "%s,\n\t", s);
      zeros = 0;
  } else {
      if (zeros == 8) {
	  fprintf(stdout, "\n\t0,");
	  zeros = 0;
      } else {
	if (zeros)
	  fprintf(stdout, " ");
	fprintf(stdout, "0,");
      }
      zeros++;
  }
}

main(){
  int i;

  fprintf(stdout,"%s",header);

  for (i = 2; i < sizeof(Vectors)/sizeof(char *); i++) {
      if (Vectors[i])
	DefineHandler(Vectors[i]);
  }
  fprintf(stdout, "%s", mid);

  for (i = 0; i < sizeof(Vectors)/sizeof(char *); i++) {
    PrintVectorName(Vectors[i]);
  }

  fprintf(stdout, "\n};\n");
  return 0;
}
