TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) uart_echo.o #gpio.o interrupt.o cpu.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


